### ISSUE TITLE
Error when firing

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-role_siki#10]
[ERROR] addons/ttt2-role_siki-master/lua/weapons/weapon_ttt2_sidekickdeagle.lua:98: attempt to index upvalue 'ttt2_sidekick_deagle_refill_conv' (a nil value)
  1. unknown - addons/ttt2-role_siki-master/lua/weapons/weapon_ttt2_sidekickdeagle.lua:98

When shooting a player

**Comment by Alf21** [comment]
Do you have the newest version?

**Comment by Alf21** [comment]
@lebroomer it could be possible that the sidekick deagle is loaded before the sidekick role is initialized. As a result, the ConVar isnt created at this moment. I think that this is leading to this issue (reasoned by the loading order). We should check this with a fallback. I suggest using CreateConVar function instead of GetConVar because it is doing the same. GetConVar makes sense if using in functions, sure. But to prevent initialization bugs, its not recommended.

**Comment by TimGoll** [comment]
But - correct me if I'm wrong - this error occured after firing the deagle. At that point everything should be loaded.

**Comment by Alf21** [comment]
no. Not if the var isnt set because it is set while loading the script. This will lead to a nil initialization. Using :GetBool() after this will result in a nil error.

**Comment by TimGoll** [comment]
okay, my bad. I get it!
