### ISSUE TITLE
Sidekick Mod #2

### ISSUE THREAD

**Issue by Mundoener** [Alf21/ttt2-role_siki#15]
The Sidekick can't win alone, so if the Jackal dies and the Sidekick is still alive, the Team Jackal can't win anymore.

**Comment by Histalek** [comment]
Are the any errors in the serverconsole or if not can you explain the situation a bit further? it is not really clear to me what exactly happened. 
~~Also it seems like something is fundamentally wrong because there should never be a sidekick without a jackal.~~

Leaving a link to your servercollection and listing what other addons you are using on the server (e.g. addons in your servers `addons` folder) helps greatly

**Comment by TimGoll** [comment]
No, there is a Sidekick mode where he stays sidekick even if the j dies

**Comment by Histalek** [comment]
Well in that case the question seems to be if the Sidekick should be able to win in that case or if it is intended that he does not

**Comment by TimGoll** [comment]
I think he should since there is no reason for him being alive otherwise

**Comment by Mundoener** [comment]
It's like Tim's saying. We're using the 2. Sidekick mode, where the Sk can kill his targets and exist without a Jackal, so he should actually be able to win the round in my opinion.
