### ISSUE TITLE
Sidekick who was previously a Detective still appears as a Detective to Innocents

### ISSUE THREAD

**Issue by AaronMcKenney** [Alf21/ttt2-role_siki#18]
If the Jackal shoots a Detective with a Sidekick Gun, they become a sidekick, which is perhaps a bit overpowered. More importantly however, the Sidekick will still be listed as a Detective in the GUI. This essentially gives the Sidekick plot armor, as no Innocent in their right minds would believe that the Detective is evil. I would prefer it if either the Detective cannot become a Sidekick, or they are at least they stop showing up as a Detective if they are turned.

**Comment by Histalek** [comment]
As far as i see it that is the intended behaviour. Every player only has knowledge about the last known role of another player, may it be through body confirmation or through that players role being publicly known (e.g. Detective). 

Two points as of why this most likely won't be changed:
- If the Information about a player being the detective vanishes you know instantly that he is a sidekick, which renders the idea of the role useless
- The idea of the role is that players who could normally trust somebody (e.g. Innocents trust the detective; traitors trust other traitors + they feel safe as innocents normally won't kill them without reason) can not trust that somebody anymore, because they could be a sidekick/jackal

Also when i play with the Jackal enabled on the server i never fully trust the detective. they are the most likely target for the jackal to shoot as sidekick after all.

**Comment by TimGoll** [comment]
Yes, this is intended bahaviour.
